name: badmincab_mobile
description: Badminton Court Allocation Board Mobile App

publish_to: 'none'
version: 20.25.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  audioplayers: ^5.2.1  # Add this for sound
  wakelock_plus: ^1.2.0 # For avoiding timer freeze during screen lock

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/beep.mp3  # Audio

# Icon Configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#6366F1"
  adaptive_icon_foreground: "assets/icon.png"